### ISSUE TITLE
Graylog

### ISSUE THREAD

**Issue by YooSunYoung** [SciCatProject/scicat-filewriter-ingest#21]
~We need to send log to graylog and be streamed locally.~

Now we just need to write integration tests for graylog.

**Comment by nitrosx** [comment]
ECDC suggested to use the following python library:
- https://pypi.org/project/graypy/

Here is an example on how it is used:
- https://github.com/ess-dmsc/forwarder/blob/5bf795ff2c27280b57386f6e7c4e38956380407e/forwarder/application_logger.py#L23

**Comment by nitrosx** [comment]
This issue has been addressed
