### ISSUE TITLE
[Refactoring] Split file omitting logics

### ISSUE THREAD

**Issue by YooSunYoung** [SciCatProject/scicat-filewriter-ingest#3]
Granular issue of #2 

We will start with splitting file omitting logics from ingestor.

Probably this part....??
https://github.com/SciCatProject/scicat-filewriter-ingest/blob/3c5c22ea4e606719e55b7999e407f18470b4e76c/ingestor_lib.py#L261-L279

**Comment by nitrosx** [comment]
@YooSunYoung should we close this issue?

**Comment by YooSunYoung** [comment]
Fixed by #61
