### ISSUE TITLE
File configuration is ignored

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/scicat-filewriter-ingest#77]
When a configuration is specified with the -c option, the settings loaded through the file are ignored as they are over written by the default options from the command lines.

Steps to re-create the issue:
- create a configuration file with the option `datasets.compute_file_hash: true`
- start the offline ingestor with -c option pointing the file above
- after starting, the option `datasets.compute_file_has` is set to false

Expected behavior:
configuration options should use default value is not specified in configuration file. If the configuration file contains the option, the value provided there should be used.
If a user specify such option on the command line, the value user specified value is the one used.

**Comment by nitrosx** [comment]
To further elaborate, this is the precedence of values for each options:

1. User provided at command line
2. Configuration value
3. Default value

**Comment by YooSunYoung** [comment]
Fixed by #78
